# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create dir
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Dependency-linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -yq xorg-dev libgtk-3-dev

      # Runs a set of commands using the runners shell
      - name: Configure
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}
        run: cmake -S $GITHUB_WORKSPACE -B build/ -DCMAKE_BUILD_TYPE=Release -A x64

      - name: Build
        working-directory: ${{runner.workspace}}
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build build/ --config Release


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
            name: MIDIVizualiser-${{matrix.os}}
            # A file, directory or wildcard pattern that describes what to upload
            path: |
              ${{runner.workspace}}/build/MIDIVisualizer
              ${{runner.workspace}}/build/x64/Release/MIDIVisualizer.exe
              ${{runner.workspace}}/build/Release/MIDIVisualizer.exe




