name: Generate release

on:
  release:
    types: 
      - published

jobs:
  build:

    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          #  cmake-opts: -D CMAKE_C_COMPILER=gcc-9 -D CMAKE_CXX_COMPILER=g++-9
          #  artifact_name: build/MIDIVisualizer
          #  asset_name: MIDIVisualizer-ubuntu.zip
          #  ffmpeg-archive: ffmpeg-linux-64-static-lgpl.zip
          - os: windows-latest
            cmake-opts: -A x64
            artifact_name: build/x64/Release/MIDIVisualizer.exe
            asset_name: MIDIVisualizer-windows-64bits.zip
            ffmpeg-archive: ffmpeg-windows-64-static-lgpl.zip
          - os: macOS-latest
            cmake-opts:
            artifact_name: build/MIDIVisualizer
            asset_name: MIDIVisualizer-macos.zip
            ffmpeg-archive: ffmpeg-osx-64-static-lgpl.zip
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies-ubuntu
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: sudo apt-get update -y && sudo apt-get install -yq xorg-dev libgtk-3-dev

      - name: Dependencies-macos
        if: matrix.os == 'macOS-latest'
        shell: bash
        run: brew install wget

      - name: Dependencies-windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: choco install wget unzip

      - name: Dependencies
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/libs
          wget -O ffmpeg.zip https://github.com/kosua20/MIDIVisualizer-dependencies/releases/latest/download/${{matrix.ffmpeg-archive}}
          unzip ffmpeg.zip
          rm ffmpeg.zip
          cp ffmpeg/share/ffmpeg/FindFFMPEG.cmake ./

      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
          cmake -S $GITHUB_WORKSPACE -B build/ -DCMAKE_BUILD_TYPE=Release ${{matrix.cmake-opts}}

      - name: Build
        working-directory: ${{runner.workspace}}
        shell: bash
        run: cmake --build build/ --config Release

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{runner.workspace}}/${{matrix.artifact_name}}
          asset_name: ${{matrix.asset_name}}
          asset_content_type: application/zip




